### PR TITLE
updates to the f.a.q.

### PR DESCRIPTION
**Pull request by RanAwaySuccessfully**
adding a section for &tags& and another one for BBcode - dunno if there should be more stuff or less or if it should be formatted differently, but this should work

### CODE REVIEW

**Comment by Xkeeper0** [comment]
I don't think bbcode formatting is applied inside the FAQ section (all it does is wrap it in some boilerplate layout), so the HTML comments are not needed and the examples won't actually render. I'll take a look at this later

**Comment by RanAwaySuccessfully** [comment]
actually there are also some &tags& that i didn't think were there (and some were removed)

if BBcode doesn't convert on the F.A.Q. page then the &tags& themselves might not convert as well

welp

**Comment by rambly** [comment]
I wrote a new version of faq.php that should actually have the BBcode displaying correctly, which I think should be displaying on my Jul fork if you want to see it?  It's using hardcoded HTML for the results.  I could have done doreplace2() on most of them, though -- I figured using HTML was probably very slightly easier on the server, but it might make it slightly more of a pain to update long-term...

@RanAwaySuccessfully and @Xkeeper0:
Is it all right with you two if I submit a separate pull request for it?  I'm new to git + GitHub, so I'm not sure how to add on to this one, or if I can even...

**Comment by RanAwaySuccessfully** [comment]
"apparently Rambly did a bunch of stuff regarding the F.A.Q. page yesterday, so I decided to update it a bit more and then update the pull request branch itself

in the process i managed to make all the branches be about four times more complicated because reasons"

that and also the code works now I guess since it doesn't need BBcode, and it's updated so all &tags& match the ones in function.php

**Comment by rambly** [comment]
Oh hi yeah.  I forgot to mention it here, sorry.

I didn't wanna put it in my own pull request yet because I wasn't sure whether or not the methodology was okay, but I'm guessing it is, so it's probably fine.

I thought about using doreplace2() directly, but I figured I'd just use HTML.  I'm also not 100% sure the escape_codeblock() will work... it *should*, but I don't really have a way to test it right now.  I'll figure that out soon.

If the commits are too messy, I can close my current pull request and do a different one with only the relevant changes, I guess.  The changes to the daily backup page/faq.php would only be in one or two commits.  I don't wanna spam #x with the GitHub bot, so...

**Comment by RanAwaySuccessfully** [comment]
The reason I didn't opt to use doreplace() is because...

\*_starts to realize the difference between doreplace() and doreplace2()_\*

Oh wait, that's actually easy to do hold on. Since it only requires the _$msg_ variable we can just parse it through that and make sure the page is always kept up to date regarding the BBcode conversions (in case any get changed later on). Or would it be preffered to keep it as HTML?

**Comment by rambly** [comment]
I was kind of thinking that... I had the option to use the function or use HTML and in the end I picked HTML for the tiny, tiny gain in efficiency.

I think using doreplace2() would be slightly more convenient to keep updated (i.e. theoretically we'd only have to touch faq.php when new BBcode gets added), enough that it's worth the probably minuscule amount of extra processing.  So, my recommendation would be switching over, although it's ultimately up to Xkeeper...

**Pull request merged**
